from fastapi import APIRouter

from app.api.v1.endpoints import admin, analytics, auth, count_session, counterparty, customers, health, inventory, inventory_count, qinsi_scrape, rakuten_credentials, rakuten_download, rakuten_label, rakuten_order, status, telegram, telegram_users, trade_allocations, trade_containers, warehouses

api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(status.router, prefix="/status", tags=["status"])
api_router.include_router(inventory_count.router, prefix="/inventory-count", tags=["inventory-count"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(warehouses.router, prefix="/warehouses", tags=["warehouses"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(qinsi_scrape.router, prefix="/qinsi", tags=["qinsi-scrape"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(rakuten_order.router, prefix="/rakuten", tags=["rakuten-order"])
api_router.include_router(rakuten_label.router, prefix="/rakuten", tags=["rakuten-label"])
api_router.include_router(rakuten_credentials.router, prefix="/rakuten", tags=["rakuten-credentials"])
api_router.include_router(rakuten_download.router, prefix="/rakuten", tags=["rakuten-download"])
api_router.include_router(telegram.router, prefix="/telegram", tags=["telegram"])
api_router.include_router(telegram_users.router, prefix="/telegram-users", tags=["telegram-users"])
api_router.include_router(trade_allocations.router, prefix="/trade", tags=["trade-allocations"])
api_router.include_router(trade_containers.router, prefix="/containers", tags=["trade-containers"])
api_router.include_router(count_session.router, prefix="/counting", tags=["counting"])
api_router.include_router(counterparty.router, prefix="/counterparty", tags=["counterparty"])
